# Generated by Django 3.0.2 on 2020-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('group_name', models.CharField(max_length=25)),
                ('faculty_name', models.CharField(max_length=25)),
                ('course_name', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
