# Generated by Django 3.0.2 on 2020-01-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='faculty_name',
            new_name='curator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
    ]
