# Generated by Django 3.0.2 on 2020-01-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200111_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.CharField(max_length=128),
        ),
    ]
