# Generated by Django 3.0.2 on 2020-01-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200125_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
    ]
