# Generated by Django 3.0.2 on 2020-02-04 22:23

from django.db import migrations


def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id', 'telephone').iterator():
        student.telephone = ''.join(x for x in student.telephone if x.isdigit())
        student.save(update_fields=['telephone'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200201_2216'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
