# Generated by Django 3.0.2 on 2020-02-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200210_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=40, unique=True),
        ),
    ]
