# Generated by Django 3.0.2 on 2020-02-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200215_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST')])),
                ('time_delta', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
