# Generated by Django 3.0.2 on 2020-02-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
