# Generated by Django 3.0.2 on 2020-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200204_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=40, unique=True),
        ),
    ]
