# Generated by Django 3.0.2 on 2020-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200107_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_number',
            field=models.CharField(default=612, max_length=3),
            preserve_default=False,
        ),
    ]
