# Generated by Django 3.0.2 on 2020-01-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_group_group_number'),
    ]

    operations = [
        migrations.AlterField(model_name='group', name='group_number', field=models.IntegerField()),
    ]
